---
#  info - https://mike42.me/blog/2018-03-automating-lxc-container-creation-with-ansible
#- hosts: greenbone
#  become: yes
#  remote_user: vagrant
#  serial: 1
#  tasks:
#  - wait_for: host={{ ansible_host }} port=22
#
#  - name: container key is up-to-date locally
#    shell: ssh-keygen -R {{ ansible_host }}; (ssh-keyscan {{ ansible_host }} >> ~/.ssh/known_hosts)
#
- hosts: greenbone
  become: yes
  remote_user: vagrant
  gather_facts: false
  vars:
  tasks:

  - name: remove key from known_hosts
    shell: ssh-keygen -R 192.168.30.101
    connection: local
    become: no
    #with_items: "{{ groups[ 'lxc_containers' ] }}"
    #when: hostvars[item]['ansible_host'] is defined
    ignore_errors: yes

  - name: container key is up-to-date locally
    shell: ssh-keyscan -H 192.168.30.101 >> ~/.ssh/known_hosts
    connection: local
    become: no
    #with_items: "{{ groups[ 'lxc_containers' ] }}"
    #when: hostvars[item]['parent'] == inventory_hostname and hostvars[item]['ansible_host'] is defined

  - name: Install Python and other bayer... ;)
    raw: which python || (apt -y update && apt install -y python)

  - name: Installing other tools package's
    apt:
      name:
        - mc
        - wget
        - ntp
        - net-tools
        - aptitude
        - tcpdump
        - python-pip
      state: latest

- hosts: greenbone
  become: yes
  remote_user: vagrant
  gather_facts: no
  vars:
  roles:
    - openvas-raw
