---
- hosts: proxmox-node
  gather_facts: no
  vars:
  - ansible_user: root
  - ansible_password: qazwsx
  roles:
    - ansible-role-proxmox-lxc

- hosts: greenbone-pve
  connection: greenbone_pve
  become: true 
  serial: 1
  tasks:
  - wait_for: host={{ ansible_host }} port=22
  - name: container key is up-to-date locally
    shell: ssh-keygen -R {{ ansible_host }}; (ssh-keyscan {{ ansible_host }} >> ~/.ssh/known_hosts)

- hosts: greenbone-pve
  gather_facts: no
  vars:
  - ansible_user: root
  - ansible_password: {{containerpass}} 
 tasks:
  - name: SET  DNS Serwer - LX-NET DHCP IS OFF
    raw: sed -i -e 's@^name.*@nameserver 8.8.8.8@' /etc/resolv.conf
  - name: install python on target machines
    raw: which python || (apt -y update && apt install -y python)

- hosts: greenbone-pve
  gather_facts: no
  vars:
  - ansible_user: root
  - ansible_password: {{containerpass}}
  roles:
    - ansible-role-openvas-raw

