---
  #  echo -n YourPass | makepasswd --crypt-md5 --clearfrom - 
- hosts: proxmox-node
  become: no
  remote_user: root
  gather_facts: no
  vars:
    - $1$hr9o9P44$K1WifqO5CO1jCeC4apVSF0
  roles:
    - ansible-role-proxmox-lxc

- hosts: 
  connection: greenbone-pve
  become: false
  serial: 1
  tasks:
  - wait_for: host={{ ansible_host }} port=22
  - name: container key is up-to-date locally
    shell: ssh-keygen -R {{ ansible_host }}; (ssh-keyscan {{ ansible_host }} >> ~/.ssh/known_hosts)

- hosts: greenbone-pve
  gather_facts: no
  ansible_user: root
  vars:
  - password: $1$WT.sL5Xf$6nKPUCrV9hFX15l.1ULUj0
  tasks:
  - name: SET  DNS Serwer - LX-NET DHCP IS OFF
    raw: sed -i -e 's@^name.*@nameserver 8.8.8.8@' /etc/resolv.conf
  - name: install python on target machines
    raw: which python || (apt -y update && apt install -y python)

- hosts: greenbone-pve
  become: no 
  remote_user: root
  gather_facts: no
  vars:
    - password: $1$WT.sL5Xf$6nKPUCrV9hFX15l.1ULUj0
  roles:
    - ansible-role-openvas-raw

