---
#  info - https://mike42.me/blog/2018-03-automating-lxc-container-creation-with-ansible
#  użyj klawiszy keyscan, aby uzyskać klucze SSH dla każdej maszyny, gdy tylko będzie ona dostępna.
#- hosts: greenbone
#  become: yes
#  remote_user: vagrant
#  serial: 1
#  tasks:
#  - wait_for: host={{ ansible_host }} port=22
#
#  - name: container key is up-to-date locally
#    shell: ssh-keygen -R {{ ansible_host }}; (ssh-keyscan {{ ansible_host }} >> ~/.ssh/known_hosts)
#

  # Przez SSH i zainstaluj Pythona i inne pakiety
- hosts: greenbone
  become: yes
  remote_user: vagrant
  gather_facts: false
  vars:
  tasks:

#  - name: Wait for ssh to come up
#    wait_for: host=192.168.30.101 port=22 delay=10  timeout=300
#    #with_items: "{{ groups[ 'lxc_containers' ] }}"
#    #when: hostvars[item]['parent'] == inventory_hostname and hostvars[item]['state'] is defined

  - name: remove key from known_hosts
    shell: ssh-keygen -R 192.168.30.101
    connection: local
    become: no
    #with_items: "{{ groups[ 'lxc_containers' ] }}"
    #when: hostvars[item]['ansible_host'] is defined
    ignore_errors: yes

  - name: container key is up-to-date locally
    shell: ssh-keyscan -H 192.168.30.101 >> ~/.ssh/known_hosts
    connection: local
    become: no
    #with_items: "{{ groups[ 'lxc_containers' ] }}"
    #when: hostvars[item]['parent'] == inventory_hostname and hostvars[item]['ansible_host'] is defined

  - name: Install Python and other bayer... ;)
    raw: which python || (apt -y update && apt install -y python)

  - name: Installing tools package's
    apt:
      name:
        - mc
        - wget
        - ntp
        - net-tools
        - aptitude
        - tcpdump
        - python-pip
      state: latest

# - name: Dodanie klucza www.atomicorp.com
#   raw: wget -q https://www.atomicorp.com/RPM-GPG-KEY.atomicorp.txt -O- |  apt-key add -
 
- hosts: greenbone
  become: yes
  remote_user: vagrant
  gather_facts: no
  vars:
  roles:
    - openvas-raw
