---
  # Ansible 2.7 Ubuntu Bionic
  # -------------------------
- include: sshd-keepalive.yml
  tags: [ sshd, sshd-config ]

- include: redis-install.yml
  tags: [ redis, redis-install ]

- include: openvas-install.yml
  tags: [ openvas, openvas-install ]

- include: openvas-config.yml
  tags: [ openvas, openvas-config ]

- include: openvas-rebuild.yml
  tags: [ openvas, openvas-rebuild ]

- include: openvas-msg.yml
  tags: [ openvas, openvas-msg ]
