---
# ansible 2.7
- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Installing Redis and pcregrep package
  package:
    name:
      - redis
      - pcregrep
    state: latest

- name: SET Redis unixsocket for OpenVAS 
  raw: sed -i -e 's@^\(# \)\{0,1\}unixsocket .*@unixsocket /var/run/redis/redis.sock@' /etc/redis/redis.conf

- name: SET Redis unixsocketperm for OpenVAS
  raw: sed -i -e 's@^\(# \)\{0,1\}unixsocketperm .*@unixsocketperm 770@' /etc/redis/redis.conf
#  notify:
#    - restart redis
- name: Systemctl restart Redis service 
  raw: systemctl restart redis
